package Server.Database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/** Создаёт JDBC-соединения и подготавливает структуру базы данных. */
public class DatabaseManager {

    private static final String URL = "jdbc:postgresql://pg:5432/studs";
    private final String username;
    private final String password;

    public DatabaseManager() throws IOException {

        Path path = Path.of(System.getProperty("user.home"), ".pgpass");
        try (BufferedReader reader = Files.newBufferedReader(path)) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank() || line.startsWith("#")) continue;
                String[] fields = line.split(":", 5);
                if (fields.length == 5
                        && matches(fields[0], "pg")
                        && matches(fields[1], "5432")
                        && matches(fields[2], "studs")
                        && !fields[3].isBlank() && !fields[4].isEmpty()) {
                    username = fields[3];
                    password = fields[4].replace("\\:", ":").replace("\\\\", "\\");
                    return;
                }
            }
        }
        throw new IOException("В ~/.pgpass нет реквизитов для pg:5432:studs.");
    }

    private static boolean matches(String value, String expected) {
        return value.equals("*") || value.equals(expected);
    }

    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, username, password);
    }

    public void initialize() throws SQLException {
        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {

            statement.executeUpdate("""
                    CREATE SEQUENCE IF NOT EXISTS lab7_product_id_seq
                    START WITH 1 INCREMENT BY 1
                    """);

            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS lab7_users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        login VARCHAR(100) NOT NULL UNIQUE,
                        password_hash CHAR(128) NOT NULL
                    )
                    """);

            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS lab7_products (
                        id BIGINT PRIMARY KEY DEFAULT nextval('lab7_product_id_seq'),
                        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
                        coordinate_x DOUBLE PRECISION NOT NULL,
                        coordinate_y REAL NOT NULL,
                        creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        price BIGINT NOT NULL CHECK (price > 0),
                        part_number TEXT,
                        unit_of_measure VARCHAR(30),
                        owner_name TEXT NOT NULL CHECK (length(trim(owner_name)) > 0),
                        owner_birthday DATE NOT NULL,
                        owner_height BIGINT NOT NULL CHECK (owner_height > 0),
                        owner_weight BIGINT CHECK (owner_weight > 0),
                        owner_nationality VARCHAR(30),
                        creator_id BIGINT NOT NULL REFERENCES lab7_users(id)
                    )
                    """);
        }
    }
}
